### PR TITLE
Fixing Build Error Python 2.6

### PR DESCRIPTION
**Pull request by tobiashochguertel**
The Build Status of your project is not showing good. I checked the problem and fixed it.

Now TravisCI can build even with python 2.6.

### CODE REVIEW

**Comment by tobiashochguertel** [comment]
Please change the Readme.md Build Status after merge back to your Travis CI Env.

``` [build status](http://travis-ci.org/FND/markdown-checklist) ```

**Comment by FND** [comment]
Thanks for this, much appreciated!

However, I'm tempted to just drop support for Python 2.6 altogether: Python Markdown itself doesn't seem to support Python 2.6 anymore, so we might as well follow suit. More generally, I reckon it's reasonable to expect at least Python 2.7 these days, no?

**Comment by tobiashochguertel** [comment]
I'm not familiar with Python. I think and good way to get an answer is to check which python version is currently avaiable by common linux distributations and how much download traffic python 2.6 gets on sourceforge.

I use this Plugin with Plugin OmniMarkupPreviewer for Sublime Text 3. I want to write Checklists in Markdown. Your implementation of checklist is more usable as my own implementation.

**Comment by FND** [comment]
As far as I'm aware, any modern OS (i.e. recent versions of whatever Linux distro or OS X) comes with Python 2.7 - it's just a few legacy releases (e.g. Debian Squeeze) that are still stuck with Python 2.6.

Also, even if we don't actively support Python 2.6 anymore, it should still work (as long as `importlib` is available of course).

> I use this Plugin with Plugin OmniMarkupPreviewer for Sublime Text 3.

That's intriguing - thanks for letting me know!

**Pull request closed without merging**
